# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-22 13:32
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('djangocms_blog', '0027_post_date_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_banner', slotname='post_banner', to='cms.Placeholder'),
        ),
    ]
