# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-23 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_auto_20170331_1251'),
        ('djangocms_blog', '0028_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='djangocms_blog.BlogCategory', verbose_name='helper'),
        ),
    ]
