# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-23 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0029_auto_20170423_1628'),
        ('djangocms_blog', '0028_auto_20170304_1040'),
    ]

    operations = [
    ]
