# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-02 15:19
from __future__ import unicode_literals

import aldryn_apphooks_config.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blog', '0030_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='app_config',
            field=aldryn_apphooks_config.fields.AppHookConfigField(help_text='When selecting a value, the form is reloaded to get the updated default', null=True, on_delete=django.db.models.deletion.CASCADE, to='djangocms_blog.BlogConfig', verbose_name='app.config'),
        ),
        migrations.AlterField(
            model_name='blogconfigtranslation',
            name='app_title',
            field=models.CharField(default='Blog-News', max_length=234, verbose_name='application title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Optionally connect this post to a club.', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.Club'),
        ),
    ]
